
## Dynamic Loading

OpenMethod supports dynamic loading on operating systems that are capable of
handling C++ templates correctly during dynamic link. A dynamic library can add
classes, methods and overriders to an existing policy. `initialize` must then be
called to rebuild the dispatch tables.

This leads to a problem: any `virtual_ptr` in existence before `initialize` is
called again becomes invalid. This also applies to vptrs that are stored inside
objects by `with_vptr`.

NOTE: This applies only to cases where a dynamic library adds to an _existing_
policy. Even if the dynamic library itself uses open-methods, for example as an
implementation detail, but it uses its own policy, there is no issue.

The solution is to use a policy that contains the `indirect_vptr` facet. Instead
of storing the vptr directly, it stores a reference to the vptr.

Here is an example:

[source,c++]
----
include::{exampledir}/dl.hpp[tag=header]
----

NOTE: The policy must be passed to the method as well as the
`virtual_ptr`{empty}s.

The `indirect_vptr` facet tells `virtual_ptr` to use a pointer to the vptr. Even
tough the value of the vptr changes when `initialize` is called, the vptrs are
stored in the same place (the policy's `static_vptr<Class>` variables).

We can now register the classes and and provide an overrider:

[source,c++]
----
include::{exampledir}/dl_main.cpp[tag=main]
----

At this point we only have one overrider. Animals of all species ignore one
another:

[source,c++]
----
include::{exampledir}/dl_main.cpp[tag=before_dlopen]
----

Let's load a dynamic library containing this code:

[source,c++]
----
include::{exampledir}/dl_shared.cpp[tag=dl_shared]
----

Now back to `main`:

[source,c++]
----
include::{exampledir}/dl_main.cpp[tag=dlopen]
----

After unloading the library, we must call `initialize` again:

[source,c++]
----
include::{exampledir}/dl_main.cpp[tag=after_dlclose]
----
