[#tutorial]
# Tutorial
:toc:
:toc-title:
:idprefix: tutorial_
:examplesdir: ../examples

## Hello World

Consider the following program, intended to demonstrate the basics of virtual
functions:

[source,c++]
----
include::{examplesdir}/virtual_func.cpp[tag=code]
----

We are going to rewrite it with open-methods.

First we remove the virtual functions from the domain classes:

[source,c++]
----
include::{examplesdir}/hello_world.cpp[tag=domain_classes]
----

Note that the Animal classes do not depend on iostreams anymore. This is a major
advantage of open-methods over virtual functions: they make it possible to
better organize dependencies.

Let's define `poke`. First we need to include the library's main header (and
`<iostream>`). It defines a few macros, and injects a name - `virtual_ptr` - in
the global namespace.

[source,c++]
----
include::{examplesdir}/hello_world.cpp[tag=method]
----

This defines a free function called `poke`, which takes two arguments. The first
is the `ostream`. The second argument corresponds to the implicit `this` pointer
in the virtual function. It is now an explicit argument. Just like for virtual
functions, the exact function to execute is selected on the basis of the
argument's _dynamic_ type.

NOTE: open-method signatures consist of types only. They may *not* contain
parameter names.

Unlike virtual functions, there is no such thing as a pure open-method that
would make a class abstract. It is not possible to determine if an overrider is
available from looking at just the current translation unit.

Let's add overriders for `Cat` and `Dog`:

[source,c++]
----
include::{examplesdir}/hello_world.cpp[tag=overriders]
----

`Bulldog::poke` calls the `poke` it overrides in its `Dog` base. The equivalent
for open-methods is `next`, a function that is available only inside the body of
an overrider.  It calls the next most specific overrider, i.e. what would have
been called if the current override did not exist.

[source,c++]
----
include::{examplesdir}/hello_world.cpp[tag=next]
----

All classes involved in open-method calls need to be registered using the
`BOOST_OPENMETHOD_CLASSES` macro:

[source,c++]
----
include::{examplesdir}/hello_world.cpp[tag=classes]
----

Classes can be registered incrementally, as long as all the direct bases of a
class appear in the same call to `BOOST_OPENMETHOD_CLASSES`. For example,
`Bulldog` can be added in a second call, as long as `Dog` is listed as well:

[source,c++]
----
// in animals.cpp
BOOST_OPENMETHOD_CLASSES(Animal, Cat, Dog);

// in bulldog.cpp
BOOST_OPENMETHOD_CLASSES(Dog, Bulldog);
----

`boost::openmethod::initialize();` must be called before any open-method call.
It builds the dispatch tables. Typically this is done in `main`:

[source,c++]
----
include::{examplesdir}/hello_world.cpp[tag=main,indent=0]
----

`poke` is called like an ordinary function (which it is). `virtual_ptr` has a
conversion constructor that takes a reference to an object, passing it the
animals by reference. `virtual_ptr`

[source,c++]
----
include::{examplesdir}/hello_world.cpp[tag=call]
----

NOTE: `virtual_ptr` is more like a reference than a pointer: it cannot be null,
and it cannot be re-assigned. The only reason why it is not called `virtual_ref`
is to save the name in case it becomes possible to overload the dot operator in
future versions of C++.

## Multiple Dispatch

A method can have more than one `virtual_ptr` parameter. For example:

[source,c++]
----
include::{examplesdir}/hello_world.cpp[tag=multi]
----

[source,c++]
----
include::{examplesdir}/hello_world.cpp[tag=multi_call,indent=0]
----

The appropriate overrider is selected using the same process similar to overload
resolution. If there is no single overrider that is more specialized than all
the others, the return type is used as a tie-breaker, _if_ it is covariant with
the return type of the base method. If there is still no unique overrider, one
of the overriders is chosen arbitrarily.

## Multiple Inheritance

Multiple inheritance is supported, with the exception of repeated inheritance.

Virtual inheritance is supported, but it incurs calls to `dynamic_cast` to cast
the method's arguments to the types required by the overrider.

## Friendship

OpenMethod places overriders in specializations of a template named after the
method. Macro `BOOST_OPENMETHOD_OVERRIDERS` returns that name. We can thus grant
friendship to all the overriders of all the methods that have the same name:

[source,c++]
----
include::{examplesdir}/friendship.cpp[tag=friend_all]
----

Be aware, though, that any method called `poke` -

[source,c++]
----
include::{examplesdir}/friendship.cpp[tag=forward]
----

[source,c++]
----
include::{examplesdir}/friendship.cpp[tag=friend]
----


## Performance

Open methods are almost as fast as ordinary virtual member functions when
compiled with optimization. For both clang and gcc, dispatching a call to a
method with one virtual argument takes 15-30% more time than calling the
equivalent virtual member function (unless the call goes through a virtual base,
which requires a dynamic cast). If the body of the method does any amount of
work, the difference is unnoticeable.

Here is the assembly code generated by clang for the `poke` method compiled for
the x64 architecture (variable names have been shortened for readability):

[source,asm]
----
	mov	    rax, qword ptr [rsi]
	mov	    rdx, qword ptr [rip + hash_mult]
	imul	rdx, qword ptr [rax - 8]
	movzx	ecx, byte ptr [rip + hash_shift]
	shr	    rdx, cl
	mov	    rax, qword ptr [rip + vptrs]
	mov	    rax, qword ptr [rax + 8*rdx]
	mov	    rcx, qword ptr [rip + poke::slots_strides]
	mov	    rax, qword ptr [rax + 8*rcx]
	jmp	    rax
----

The library uses a collision-free hash table to find the dispatch table
(v-table) from the object's native type id (). The hash function is very simple
and very fast: `H(obj) = (&typeid(obj) * M) >> S`. The result is the index of
the open-method v-table in a global array of v-tables.

This code performs the following logical steps. When a step contains multiple
instructions, they can be executed in parallel on modern processors. The exact
order in which the steps are executed depends on the processor.

1. Load the two hash function factors (M and S), a pointer to a hash table,
   the v-table pointer from the object, and the offset of the method in the
   v-table.

2. Multiply the address of the `type_info` by M.

3. Shift the result right by S.

4. Load the v-table pointer from the global array of v-tables.

5. Load the function pointer from the v-table.

6. Call (or jump to) the function.

Analyzing the code with tools like uiCA or llvm-mca shows a throughput of 4
cycles per dispatch. Comparatively, calling a native virtual functions takes one
cycle. However, the difference is amortized by the time spent passing the
arguments and returning from the function; plus, of course, executing the body
of the function.

Micro benchmarks suggest that the overhead of dispatching an open-methods with a
single virtual argument is between 30% and 50% slower than calling the
equivalent virtual function, if the body is empty.

## virtual_ptr

The seven first instructions in the assembly code above look up the v-table for
the object. The result will always be the same for the same object. Therefore,
that pointer can be re-used for subsequent calls.

`virtual_ptr` is a fat pointer that contains two pointers: one to the object,
and the other to the v-table. Incidentally, this is how Rust and Golang
implement polymorphism.

`virtual_ptr`{empty}s are used in place of `virtual_<&>`. They can be passed
through to overriders, which can re-use them to make further method calls, or
stored in objects. For example:

[source,c++]
----
BOOST_OPENMETHOD(yell, (std::ostream&, virtual_ptr<Animal>), void);

BOOST_OPENMETHOD_OVERRIDE(
    yell, (std::ostream & os, virtual_ptr<Cat> cat), void) {
    os << "hiss";
}

BOOST_OPENMETHOD_OVERRIDE(
    yell, (std::ostream & os, virtual_ptr<Dog> dog), void) {
    os << "bark";
}

BOOST_OPENMETHOD(
    encounter, (std::ostream&, virtual_ptr<Animal>, virtual_ptr<Animal>), void);

BOOST_OPENMETHOD_OVERRIDE(
    encounter, (std::ostream & os, virtual_ptr<Dog> dog, virtual_ptr<Cat> cat),
    void) {
    yell(os, dog);
    os << " and chase";
}

BOOST_OPENMETHOD_OVERRIDE(
    encounter, (std::ostream & os, virtual_ptr<Cat> cat, virtual_ptr<Dog> dog),
    void) {
    yell(os, cat);
    os << " and run";
}
----

Calls to `yell` compile to three instructions:

[source,asm]
----
	mov	rax, qword ptr [rip + yell::slots_strides]
	mov	rax, qword ptr [rdx + 8*rax]
	jmp	rax
----

This executes in one cycle, like native virtual function calls.

WARNING: calling `initialize` invalidates all existing `virtual_ptr`{empty}s.

= Advanced Features

## Core API

OpenMethod provides a macro-free interface. This is useful in certain
situations, for example when combining open methods and templates.

Here is a rewrite of the Animals example.

[source,c++]
----
#include <boost/openmethod/core.hpp>

using namespace boost::openmethod;

class poke_openmethod;

using poke = method<
    poke_openmethod(std::ostream&, virtual_<Animal&>), void>;
----

An open-method is implemented as an instance of the `method` template. It takes
a function signature and a return type.

The `poke_openmethod` class acts as the method's identifier: it separates it
from other methods with the same signature. The exact name does not really
matter, and the class needs not be defined, only declared. Inventing a class
name can get tedious, so OpenMethod provides a macro for that:

[source,c++]
----
#include <boost/openmethod/macros/name.hpp>

class BOOST_OPENMETHOD_NAME(pet);

using pet = method<
    BOOST_OPENMETHOD_NAME(pet)(std::ostream&, virtual_<Animal&>), void>;
----

NOTE: BOOST_OPENMETHOD and associated macros use `BOOST_OPENMETHOD_NAME` in
their implementation. This makes it possible to mix the "macro" and "core"
styles.

The method can be called via the nested function object `fn`:

[source,c++]
----
poke::fn(std::cout, animal);
----

Overriders are ordinary functions, added to a method using the nested template
`override`:

[source,c++]
----
auto poke_cat(std::ostream& os, Cat& cat, void) {
    os << "hiss";
}

static poke::override<poke_cat> override_poke_cat;
----

NOTE: `override` can register more than one overrider.

In C++26, we can use `_` instead of inventing an identifier. Otherwise,
OpenMethod provides a small convenience macro:

[source,c++]
----
#include <boost/openmethod/macros/register.hpp>

auto poke_dog(std::ostream& os, Dog& dog, void) {
    os << "bark";
}

BOOST_OPENMETHOD_REGISTER(poke::override<poke_dog>);
----

`next` is available from the method's nested `next` template:

[source,c++]
----

auto poke_bulldog(std::ostream& os, Bulldog& dog, void) -> void {
    poke::next<poke_bulldog>(os, dog);
    os << " and bite";
}

BOOST_OPENMETHOD_REGISTER(poke::override<poke_bulldog>);
----

NOTE: Since the function uses itself as a template argument in its body, its
return type cannot be deduced. It must be specified explicitly, either by using
the old style or a trailing return type.


Why not call `poke_dog` directly? That may be the right thing to do; however,
keep in mind that, in a real program, a translation unit is not necessarily
aware of the overriders added elsewhere - especially in presence of dynamic
loading.

[source,c++]
----
BOOST_OPENMETHOD_CLASSES(Animal, Cat, Dog, Bulldog);
----

[source,c++]
----


int main() {
    boost::openmethod::initialize();

    Animal&& a = Cat();
    Animal&& b = Dog();

    poke(std::cout, a); // prints "hiss"
    poke(std::cout, b); // prints "bark"

    return 0;
}
----

## Policies and Facets

Methods and classes are scoped in a policy. A method can only reference classes
registered in the same policy. If a class is used as a virtual parameter in
methods using different policies, it must be registered with each of them.

Class templates `use_classes`, `method`, `virtual_ptr`, and macros
`BOOST_OPENMETHOD` and `BOOST_OPENMETHOD_CLASSES`, accept an additional
argument, a policy class, which defaults to `policies::debug` in debug builds,
and `policies::release` in release builds.

A policy has a collection of _facets_. Facets control how type information is
obtained, how vptrs are fetched, how errors are handled and printed, etc. Some
are used in `initialize` and method dispatch; some are used by other facets in
the same policy as part of their implementation. See the reference for a list of
facets and stock implementations.

`policies::release` contains the following facets:

[cols="1,1,1"]
|===
|facet |implementation |role

| rtti
| std_rtti
| provide type information for classes and objects

| vptr
| vptr_vector
| store vptrs in a global vector

| type_hash
| fast_perfect_hash
| hash type id to an index in a vector

| error_handler
| vectored_error_handler
| call a `std::function` when an error occurs

|===

`policies::debug` contains the same facets as `release`, plus a few more:

[cols="1,1,1"]
|===
|facet |implementation |role

| runtime_checks
|
| enable runtime checks

| error_output
| basic_error_output
| print error descriptions to `stderr`

| trace_output
| basic_trace_output
| make `initialize` print information about dispatch table construction to  `stderr`

|===

Policies, and some facets, have static variables. When it is the case, they are
implemented as CRTP classes.

Policies can be created from scratch, using the `basic_policy` template, or by
adding or removing facets from existing policies. For example, `policies::debug`
is a tweak of `policies::release`:

[source,c++]
----
struct debug : release::fork<debug>::add<
                   runtime_checks, basic_error_output<debug>,
                   basic_trace_output<debug>> {};
----

`fork` creates a new policy from an existing one, substituting the new policy
to the original one in all the CRTP classes. `add` adds three facets, two of
which have state.

`boost::openmethod::policies::default_` is an alias to the `release` or the
`debug` policy, depending on the value of preprocessor symbols `NDEBUG`. The
default policy can be overriden by defining the macroprocessor symbol
`BOOST_OPENMETHOD_DEFAULT_POLICY` _before_ including
`<boost/openmethod/core.hpp>`. The value of the symbol is used as a default
template parameter for `use_classes`, `method`, `virtual_ptr`, and others. Once
the `core` header has been included, changing `BOOST_OPENMETHOD_DEFAULT_POLICY`
has no effect. See below for examples.

## Error Handling

When an error is encountered, the program is terminated by a call to `abort`. If
the policy contains an `error_handler` facet, its `error` template member
function is called with an object identifying the error. The `release` and
`debug` policies implement the error facet with `vectored_error_handler`, which
wraps the error object in a variant, and calls a `std::function` which can be
set by the user. The function can throw an exception to prevent program
termination. The default value for the function prints a description of the
error to `stderr` in the `debug` policy, and does nothing in the `release.`

Error handling can be customized by setting the function:

[source,c++]
----
BOOST_OPENMETHOD_CLASSES(Animal, Cat, Dog);

BOOST_OPENMETHOD(trick, (std::ostream&, virtual_<Animal&>), void);

BOOST_OPENMETHOD_OVERRIDE(trick, (std::ostream & os, Dog& dog), void) {
    os << "spin\n";
}

int main() {
    namespace bom = boost::openmethod;
    bom::initialize();

    bom::policies::default_::set_error_handler([](const auto& error) {
        std::visit([](auto&& arg) { throw arg; }, error);
    });

    Cat felix;
    Dog hector, snoopy;
    std::vector<Animal*> animals = {&hector, &felix, &snoopy};

    for (auto animal : animals) {
        try {
            trick(std::cout, *animal);
        } catch (bom::not_implemented_error) {
            std::cerr << boost::core::demangle(typeid(*animal).name())
                      << "s don't perform tricks\n";
        }
    }

    return 0;
}
----

[source,console]
----
spin
Cats don't perform tricks
spin
----

The same result can be achieved by creating a policy that uses the `throw_error`
facet implementaion.

[source,c++]
----
namespace bom = boost::openmethod;

struct throwing_policy
    : bom::policies::default_::fork<throwing_policy>::replace<
          bom::policies::error_handler, bom::policies::throw_error> {};

BOOST_OPENMETHOD_CLASSES(Animal, Cat, Dog, throwing_policy);

BOOST_OPENMETHOD(
    trick, (std::ostream&, virtual_<Animal&>), void, throwing_policy);

BOOST_OPENMETHOD_OVERRIDE(trick, (std::ostream & os, Dog& dog), void) {
    os << "spin\n";
}

int main() {
    bom::initialize<throwing_policy>();

    Cat felix;
    Dog hector, snoopy;
    std::vector<Animal*> animals = {&hector, &felix, &snoopy};

    for (auto animal : animals) {
        try {
            trick(std::cout, *animal);
        } catch (bom::not_implemented_error) {
            std::cerr << boost::core::demangle(typeid(*animal).name())
                      << "s don't perform tricks\n";
        }
    }

    return 0;
}
----

## Custom RTTI

Stock policies use the `std_rtti` implementation of `rtti`. Here is its full
source:

[source,c++]
----
struct std_rtti : rtti {
    template<typename T>
    static type_id static_type() {
        return reinterpret_cast<type_id>(&typeid(T));
    }

    template<typename T>
    static type_id dynamic_type(const T& obj) {
        return reinterpret_cast<type_id>(&typeid(obj));
    }

    template<class Stream>
    static void type_name(type_id type, Stream& stream) {
        stream << reinterpret_cast<const std::type_info*>(type)->name();
    }

    static std::type_index type_index(type_id type) {
        return std::type_index(*reinterpret_cast<const std::type_info*>(type));
    }

    template<typename D, typename B>
    static D dynamic_cast_ref(B&& obj) {
        return dynamic_cast<D>(obj);
    }
};
----

* `static_type` is used by class registration, by `virtual_ptr`'s "final"
    constructs, and to format error and trace messages. `T` is not restricted to
    the classes that appear as virtual parameters. This function is required.

* `dynamic_type` is used to locate the v-table for an object. This function is
    required, unless only the `virtual_ptr` "final" constructs are used.

* `type_name` writes a representation of `type` to `stream`. It is used to format
    error and trace messages. `Stream` is a lighweight version of `std::ostream`
    with reduced functionality. It only supports insertion of `const char*`,
    `std::string_view`, pointers and `std::size_t`. This function is optional;
    if not provided, "type_id(_type_)" is written.

* `type_index` returns an object that _uniquely_ identifies a class. Some forms
    of RTTI (most notably, C++'S `typeid` operator) do not guarantee that the
    type information object for a class is unique within the same program. This
    function is optional; if not provided, `type` is assumed to be unique, and
    used as is.

* `dynamic_cast_ref`casts `obj` to class `D`. `B&&` is either a lvalue reference
    (possibly cv-qualified) or a rvalue reference. `D` has the same reference
    category (and cv-qualifier if applicable) as `B`. This function is required
    only if virtual inheritance is used in the class hierarchies involved with
    open-methods.

Consider a custom RTTI implementation:

[source,c++]
----
struct Animal {
    Animal(unsigned type) : type(type) {
    }

    virtual ~Animal() = default;

    unsigned type;
    static constexpr unsigned static_type = 1;
};

struct Cat : Animal {
    Cat() : Animal(static_type) {
    }

    static constexpr unsigned static_type = 2;
};

// ditto for Dog
----

This scheme has an interesting property: its type ids are monotonically
allocated in a small, dense range. Thus, we don't need to hash them. We can use
them as indexes in the table of vptrs.

This time we are going to replace the default policy globally. First we need to
define the custom RTTI facet. We must _not_ include
`<boost/openmethod/core.hpp>` or any header that includes it yet.

Here is the facet implementation:

[source,c++]
----
#include <boost/openmethod/policies/core.hpp>
#include <boost/openmethod/policies/vptr_vector.hpp>

namespace bom = boost::openmethod;

struct custom_rtti : bom::policies::rtti {
    template<typename T>
    static bom::type_id static_type() {
        if constexpr (std::is_base_of_v<Animal, T>) {
            return T::static_type;
        } else {
            return 0;
        }
    }

    template<typename T>
    static bom::type_id dynamic_type(const T& obj) {
        if constexpr (std::is_base_of_v<Animal, T>) {
            return obj.type;
        } else {
            return 0;
        }
    }
};
----

This facet is quite minimal. It would not produce good error or trace messages,
so we will not keep the related facets. It does not support virtual inheritance.

This time we will create a policy from scratch. For that we use the
`basic_policy` CRTP template:

[source,c++]
----

struct custom_policy
    : bom::policies::basic_policy<
          custom_policy, custom_rtti,
          bom::policies::vptr_vector<custom_policy>> {};

#define BOOST_OPENMETHOD_DEFAULT_POLICY custom_policy
----

Now we can include the other headers:

[source,c++]
----
#include <boost/openmethod.hpp>
#include <boost/openmethod/compiler.hpp>

BOOST_OPENMETHOD(poke, (std::ostream&, virtual_<Animal&>), void);

BOOST_OPENMETHOD_OVERRIDE(poke, (std::ostream & os, Cat& cat), void) {
    os << "hiss";
}

BOOST_OPENMETHOD_OVERRIDE(poke, (std::ostream & os, Dog& dog), void) {
    os << "bark";
}

BOOST_OPENMETHOD_CLASSES(Animal, Cat, Dog);

int main() {
    boost::openmethod::initialize();

    std::unique_ptr<Animal> a(new Cat);
    std::unique_ptr<Animal> b(new Dog);

    poke(std::cout, *a); // prints "hiss"
    std::cout << "\n";

    poke(std::cout, *b); // prints "bark"
    std::cout << "\n";

    return 0;
}
----

This programs compiles even if standard RTTI is disabled.

## Deferred RTTI

The RTTI system assigns the types id statically. It is more common to allocate
them using a global counter, manipulated by static constructors. This is a
problem, because `static_type` is used by class registration. It may read the
custom type ids _before_ they are have been initialized.

The solution is to add the `deferred_static_rtti` to the policy; it defers
reading the type information until `initialize` is called.

This time let's support virtual inheritance as well. First the domain classes:

[source,c++]
----
struct custom_type_info {
    static unsigned last;
    unsigned id = ++last;
};

unsigned custom_type_info::last;

struct Animal {
    Animal() {
        type = type_info.id;
    }

    virtual ~Animal() = default;

    virtual void* cast_impl(unsigned target) {
        if (type_info.id == target) {
            return this;
        } else {
            return nullptr;
        }
    }

    template<class Class>
    Class* cast() {
        return reinterpret_cast<Class*>(cast_impl(Class::type_info.id));
    }

    static custom_type_info type_info;
    unsigned type;
};

custom_type_info Animal::type_info;

struct Cat : virtual Animal {
    Cat() {
        type = type_info.id;
    }

    virtual void* cast_impl(unsigned target) {
        if (type_info.id == target) {
            return this;
        } else {
            return Animal::cast_impl(target);
        }
    }

    static custom_type_info type_info;
};

custom_type_info Cat::type_info;

// ditto for Dog
----


The rtti facet is the same, with one more function:

[source,c++]
----
struct custom_rtti : bom::policies::rtti {
    // as before

    template<typename Derived, typename Base>
    static Derived dynamic_cast_ref(Base&& obj) {
        using base_type = std::remove_reference_t<Base>;
        if constexpr (std::is_base_of_v<Animal, base_type>) {
            return *obj.template cast<std::remove_reference_t<Derived>>();
        } else {
            abort(); // not supported
        }
    }
};
----

Finally, the policy contains an additional facet:

[source,c++]
----
struct custom_policy
    : bom::policies::basic_policy<
          custom_policy, custom_rtti,
          bom::policies::deferred_static_rtti, // <-- additional facet
          bom::policies::vptr_vector<custom_policy>> {};
----
