
[#virtual_ptr]

## Class template virtual_ptr

`virtual_ptr` - A fat pointer that combines a pointer to an object and a
pointer to its v-table.

### Headers

`<boost/openmethod/core.hpp>`, `<boost/openmethod.hpp>`

### Synopsis

```c++
namespace boost::openmethod {

template<class Class, class Policy = BOOST_OPENMETHOD_DEFAULT_POLICY>
class virtual_ptr {
  public:
    using element_type = Class;

    // if not specialized
    template<class Other> virtual_ptr(Other& other);
    template<class Other> virtual_ptr(virtual_ptr<Other, Policy>& other);
    template<class Other> virtual_ptr(const virtual_ptr<Other, Policy>& other);

    auto get() const -> element_type*;
    auto operator->() const -> element_type*;
    auto operator*() const -> element_type&;

    template<typename Other>
    auto cast() const -> virtual_ptr<Other, Policy>;
};

template<class Class>
virtual_ptr(Class&) -> virtual_ptr<Class, BOOST_OPENMETHOD_DEFAULT_POLICY>;

template<class Class>
inline auto final_virtual_ptr(Class& obj) -> virtual_ptr<
    Class, BOOST_OPENMETHOD_DEFAULT_POLICY>;

template<class Policy, class Class>
inline auto final_virtual_ptr(Class& obj) -> virtual_ptr<Class, Policy>;
}
```

---

### Description

*Template Parameters*

[cols="1,1"]
|===

| _Class_
| A class registered in _Policy_.


| _Policy_ | A policy. Defaults to the BOOST_OPENMETHOD_DEFAULT_POLICY
preprocessor symbol.

|===

*Specializations*

[cols="1,1"]
|===

| `template<class Class> virtual_ptr<std::shared_ptr<Class>>`
| Store the pointer to the object in a `std::shared_ptr`.

| `template<class Class> virtual_ptr<std::unique_ptr<Class>>`
| Store the pointer to the object in a `std::unique_ptr`.


| _Policy_ | The policy. Defaults to the value of the
BOOST_OPENMETHOD_DEFAULT_POLICY preprocessor symbol.

|===

---

### Type aliases

```c++
using element_type = Class;
```

The type of the object.

---

### Constructors

[source,c++]
----
template<class Other> virtual_ptr(Other& other);
----

Constructs a `virtual_ptr` from an lvalue reference to an object. The pointer to
the v-table is deduced from the object's dynamic type.

`Other` must be a class registered in `Policy`.

[source,c++]
----
template<class Other> virtual_ptr(virtual_ptr<Other, Policy>& other);
----

Construct a `virtual_ptr` from another `virtual_ptr`. The pointer to the v-table
is copied from `other`.

[source,c++]
----
template<class Other> virtual_ptr(const virtual_ptr<Other, Policy>& other);
----

Construct a `virtual_ptr` from another `virtual_ptr`. The pointer to the v-table
is copied from `other`.

---

### Observers

```c++
auto get() const -> element_type*;
```

Returns a pointer to the object.

```c++
auto operator->() const -> element_type*;
```

Returns a pointer to the object.

```c++
auto operator*() const -> element_type&;
```

Returns a reference to the object.

```c++
template<typename Other>
auto cast() const -> virtual_ptr<Other, Policy>;
```

Returns a `virtual_ptr` to the same object, cast to `Other`.

---

### Deduction guides

```c++
template<class Class>
virtual_ptr(Class&) -> virtual_ptr<Class, BOOST_OPENMETHOD_DEFAULT_POLICY>;
```

---

### Non-member functions

```c++
template<class Policy, class Class>
inline auto final_virtual_ptr(Class& obj);
template<class Class>
inline auto final_virtual_ptr(Class& obj);
```

Return a `virtual_ptr` from a reference to an object, which is assumed to be an
instance of `Class`.

The pointer to the v-table is initialized from the `Policy::static_vptr<Class>`
variable.

If `Policy` is not specified, `BOOST_OPENMETHOD_DEFAULT_POLICY` is used.
