
[#virtual_ptr]
:idprefix: virtual_ptr_

## virtual_ptr<Class, Policy>

### Description

`virtual_ptr` is a fat pointer that combines a pointer to an object and a
pointer to its v-table.

`Class` must be a class registered in `Policy`; or a smart pointer to such a
class, in which case template class `virtual_ptr_traits` must be specialized for
`Class`. Specializations for `std::unique_ptr` and `std::shared_ptr` are
provided; see the documentation of `virtual_ptr_traits` for more information.

### Synopsis

`virtual_ptr` is defined in `<boost/openmethod/core.hpp>`.

```c++
namespace boost::openmethod {

template<class Class, class Policy = BOOST_OPENMETHOD_DEFAULT_POLICY>
class virtual_ptr {
  public:
    using traits = virtual_ptr_traits<Class, Policy>;
    using element_type = typename traits::Class;
    static constexpr bool is_smart_ptr =
        virtual_ptr_traits<Class, Policy>::is_smart_ptr;

    // following require is_smart_ptr == false:
    template<class Other>
    virtual_ptr(Other& other);
    template<class Other>
    virtual_ptr(virtual_ptr<Other, Policy>& other);

    // following require is_smart_ptr == true:
    template<class Other>
    virtual_ptr_impl(const Other& other)
        requires(virtual_ptr_traits<Other, Policy>::is_smart_ptr)
    template<class Other>
    virtual_ptr_impl(Other&& other)
        requires(virtual_ptr_traits<Other, Policy>::is_smart_ptr)
    template<class Other>
    virtual_ptr(virtual_ptr<Other, Policy>&& other);

    // following is available in both cases
    template<class Other>
    virtual_ptr(const virtual_ptr<Other, Policy>& other);

    template<class Other>
    static auto final(Other&& obj);

    auto get() const -> element_type*;
    auto operator->() const -> element_type*;
    auto operator*() const -> element_type&;
    auto pointer() const -> const Class*&;

    template<typename Other>
    auto cast() const -> virtual_ptr<Other, Policy>;
};

template<class Class>
virtual_ptr(Class&) -> virtual_ptr<Class, BOOST_OPENMETHOD_DEFAULT_POLICY>;

template<class Class>
inline auto final_virtual_ptr(Class& obj) -> virtual_ptr<
    Class, BOOST_OPENMETHOD_DEFAULT_POLICY>;

template<class Policy, class Class>
inline auto final_virtual_ptr(Class& obj) -> virtual_ptr<Class, Policy>;

template<class Left, class Right, class Policy>
bool operator==(
    const virtual_ptr<Left, Policy>& left,
    const virtual_ptr<Right, Policy>& right);

template<class Left, class Right, class Policy>
bool operator!=(
    const virtual_ptr<Left, Policy>& left,
    const virtual_ptr<Right, Policy>& right);

} // namespace boost::openmethod
```

### Members

#### traits

```c++
using traits = virtual_ptr_traits<Class, Policy>;
```

The traits class for the `virtual_ptr`.

#### element_type

```c++
using element_type = typename traits::element_type;
```

The class of the object pointed to. It must be registered in `Policy`.

#### is_smart_ptr

```c++
static constexpr bool is_smart_ptr = traits::is_smart_ptr
```

`true` if the pointer to the object is a smart pointer.

#### constructors

[source,c++]
----
template<class Other>
virtual_ptr(Other& other)                             <1>

template<class Other>
virtual_ptr_impl(const Other& other);                 <2>

template<class Other>
virtual_ptr_impl(Other&& other)                       <3>

template<class Other>
virtual_ptr(const virtual_ptr<Other, Policy>& other); <4>

template<class Other>
virtual_ptr(virtual_ptr<Other, Policy>&& other);      <5>
----

<1> Constructs a `virtual_ptr` from a reference to an object. The object pointer
is set to the address of the object. The v-table pointer is deduced from the
object's dynamic type. `Other` must be a subclass of `Class`.

<2> Constructs a `virtual_ptr` from a smart pointer. The object pointer is
copied from `other`. The v-table pointer is deduced from the object's dynamic
type.

<3> Constructs a `virtual_ptr` from a smart pointer. The object pointer is moved
from `other`. The v-table pointer is deduced from the object's dynamic type.

<4> Constructs a `virtual_ptr` from a `virtual_ptr`. The object pointer and the
v-table pointer are copied from `other`.

<5> Constructs a `virtual_ptr` from a `virtual_ptr`. The object pointer is moved
from `other`. The v-table pointer is copied from `other`.

#### final

```c++
template<class Other>
static auto final(Other&& obj);
```

Constructs a `virtual_ptr` from a reference to an object, or from a smart
pointer. It is assumed that the static and dynamic types are the same. The
v-table pointer is initialized from the `Policy::static_vptr` for the class,
which needs not be polymorphic.

#### get

```c++
auto get() const -> element_type*;
```

Returns a pointer to the object.

#### operator->

```c++
auto operator->() const -> element_type*;
```

Returns a pointer to the object.

#### operator*

```c++
auto operator*() const -> element_type&;
```

Returns a reference to the object.

#### pointer

```c++
auto pointer() const;
```

Returns a reference to the object pointer, which can be either a plain pointer
or a smart pointer.

#### cast

```c++
template<typename Other>
auto cast() const -> virtual_ptr<Other, Policy>;
```

Returns a `virtual_ptr` to the same object, cast to `Other`.

### Deduction guides

```c++
template<class Class>
virtual_ptr(Class&) -> virtual_ptr<Class, BOOST_OPENMETHOD_DEFAULT_POLICY>;
```

---

### Free Aliases

#### virtual_shared_ptr

```c++
template<class Class, class Policy = BOOST_OPENMETHOD_DEFAULT_POLICY>
using virtual_shared_ptr = virtual_ptr<std::shared_ptr<Class>, Policy>;
```

Defined in `<boost/openmethod/virtual_shared_ptr.hpp>`.

#### virtual_unique_ptr

```c++
template<class Class, class Policy = BOOST_OPENMETHOD_DEFAULT_POLICY>
using virtual_unique_ptr = virtual_ptr<std::unique_ptr<Class>, Policy>;
```

Defined in `<boost/openmethod/virtual_unique_ptr.hpp>`.

### Free Functions

#### final_virtual_ptr

```c++
template<class Policy, class Class>
inline auto final_virtual_ptr(Class&& obj);

template<class Class>
inline auto final_virtual_ptr(Class&& obj);
```

Utility functions equivalent to `virtual_ptr<Class, Policy>::final(obj)`.

If `Policy` is not specified, `BOOST_OPENMETHOD_DEFAULT_POLICY` is used.

#### make_virtual_shared

```c++
template<
    class Class, class Policy = BOOST_OPENMETHOD_DEFAULT_POLICY, typename... T>
inline auto make_virtual_shared(T&&... args);
```

Defined in `<boost/openmethod/virtual_shared_ptr.hpp>`.

Creates an object using `std::make_shared` and returns a `virtual_shared_ptr` to
it. The v-table pointer is initialized from the the `Policy::static_vptr` for
the class, which needs not be polymorphic.

#### make_virtual_unique

```c++
template<
    class Class, class Policy = BOOST_OPENMETHOD_DEFAULT_POLICY, typename... T>
inline auto make_virtual_unique(T&&... args);
```

Defined in `<boost/openmethod/virtual_unique_ptr.hpp>`.

Creates an object using `std::make_unique` and returns a `virtual_unique_ptr` to
it. The v-table pointer is initialized from the the `Policy::static_vptr` for
the class, which needs not be polymorphic.

#### operator==

```c++
template<class Left, class Right, class Policy>
bool operator==(
    const virtual_ptr<Left, Policy>& left,
    const virtual_ptr<Right, Policy>& right);
```

Compares two `virtual_ptr` objects for equality.

#### operator!=

```c++
template<class Left, class Right, class Policy>
bool operator!=(
    const virtual_ptr<Left, Policy>& left,
    const virtual_ptr<Right, Policy>& right);
```

Compares two `virtual_ptr` objects for inequality.
