= xref:macros.adoc[Macro]&nbsp;BOOST_OPENMETHOD_DEFAULT_REGISTRY

Default value for Registry

== Synopsis

Defined in `&lt;https://www.github.com/boostorg/openmethod/blob/develop/include/boost/openmethod/core.hpp#L27[boost&sol;openmethod&sol;core&period;hpp]&gt;`

```cpp
#define BOOST_OPENMETHOD_DEFAULT_REGISTRY ::boost::openmethod::default_registry
```

== Description

The name of the default registry.

`BOOST_OPENMETHOD_DEFAULT_REGISTRY` is the default value for the `Registry`
template parameter of `method`, `use_classes`, and other constructs defined in
`<boost/openmethod/core.hpp>`. If it is not defined,
link:reference/boost/openmethod/default_registry.html[`default_registry`] is used.

`BOOST_OPENMETHOD_DEFAULT_REGISTRY` can be defined by a program to change the
default REGISTRY globally. Once `<boost/openmethod/core.hpp>` has been included,
redefining the symbol has no effect. To override the default REGISTRY, proceed as
follows:

1. Include headers under `boost/openmethod/policies/` as needed.
2. Create a REGISTRY class, and set `BOOST_OPENMETHOD_DEFAULT_REGISTRY`.
3. Include `<boost/openmethod/core.hpp>`.
