
## Custom RTTI

Stock registries use the `std_rtti` implementation of `rtti`. Here is its full
source:

[source,c++]
----
struct std_rtti : rtti {
    template<class Registry>
    struct fn {
        template<class Class>
        static constexpr bool is_polymorphic = std::is_polymorphic_v<Class>;

        template<class Class>
        static auto static_type() -> type_id {
            return &typeid(Class);
        }

        template<class Class>
        static auto dynamic_type(const Class& obj) -> type_id {
            return &typeid(obj);
        }

        template<typename Stream>
        static auto type_name(type_id type, Stream& stream) -> void {
            stream << boost::core::demangle(
                reinterpret_cast<const std::type_info*>(type)->name());
        }

        static auto type_index(type_id type) -> std::type_index {
            return std::type_index(
                *reinterpret_cast<const std::type_info*>(type));
        }

        template<typename D, typename B>
        static auto dynamic_cast_ref(B&& obj) -> D {
            return dynamic_cast<D>(obj);
        }
    };
};
----

* `is_polymorphic` is used to check if a class is polymorphic. This template is
  required.

* `static_type` is used by class registration, by `virtual_ptr`{empty}'s "final"
    constructs, and to format error and trace messages. `T` is not restricted to
    the classes that appear as virtual parameters. This function is required.

* `dynamic_type` is used to locate the v-table for an object. This function is
    usually required. If only the `virtual_ptr` "final" constructs are used, or
    if `boost_openmethod_vptr` is provided for all the classes in the registry, it
    can be omitted.

* `type_name` writes a representation of `type` to `stream`. It is used to format
    error and trace messages. `Stream` is a lighweight version of `std::ostream`
    with reduced functionality. It only supports insertion of `const char*`,
    `std::string_view`, pointers and `std::size_t`. This function is optional;
    if it is not provided, "type_id(_type_)" is used.

* `type_index` returns an object that _uniquely_ identifies a class. Some forms
    of RTTI (most notably, C++'s `typeid` operator) do not guarantee that the
    type information object for a class is unique within the same program. This
    function is optional; if not provided, `type` is assumed to be unique, and
    used as is.

* `dynamic_cast_ref` casts `obj` to class `D`. `B&&` is either a lvalue reference
    (possibly cv-qualified) or a rvalue reference. `D` has the same reference
    category (and cv-qualifier if applicable) as `B`. This function is required
    only in presence of virtual inheritance.

Consider a custom RTTI implementation:

[source,c++]
----
struct Animal {
    Animal(unsigned type) : type(type) {
    }

    virtual ~Animal() = default;

    unsigned type;
    static constexpr unsigned static_type = 1;
};

struct Cat : Animal {
    Cat() : Animal(static_type) {
    }

    static constexpr unsigned static_type = 2;
};

// ditto for Dog
----

This scheme has an interesting property: its type ids are monotonically
allocated in a small, dense range. Thus, we don't need to hash them. We can use
them as indexes in the table of vptrs.

This time we are going to replace the default registry globally. First we need to
define the custom RTTI policy. We must _not_ include
`<boost/openmethod/core.hpp>` or any header that includes it yet.

Here is the policy implementation:

[source,c++]
----
include::example$custom_rtti.cpp[tag=policy]
----

This policy is quite minimal. It does not support virtual inheritance. It would
not produce good error or trace messages, because types would be represented by
their integer ids.

This time we create a registry from scratch:

[source,c++]
----
include::example$custom_rtti.cpp[tag=registry]
----

Next, we include the main header. Because `BOOST_OPENMETHOD_DEFAULT_REGISTRY` is
defined, its value is used for the default registry. Then comes the usual example.

[source,c++]
----
include::example$custom_rtti.cpp[tag=example]
----

This programs works even if standard RTTI is disabled.

## Deferred RTTI

In the previous example, the RTTI system assigns type ids statically. It is more
common to allocate them using a global counter, manipulated by static
constructors. Like so:

[source,c++]
----
include::example$deferred_custom_rtti.cpp[tag=classes]
// ditto for Dog
----

This is a problem, because `static_type` is used by class registration. It may
read the custom type ids _before_ they are have been initialized.

The solution is to derive the rtti policy from `deferred_static_rtti`. It defers
reading the type information until `initialize` is called.

This time let's support virtual inheritance as well.

[source,c++]
----
include::example$deferred_custom_rtti.cpp[tag=registry]
----

The example is the same as in the previous section.
