:exampledir: ../example

## Hello World

Consider the following program, intended to demonstrate the basics of virtual
functions:

[source,c++]
----
include::example$virtual_func.cpp[tag=code]
----

We are going to rewrite this using open-methods.

First we remove the `poke` virtual functions from the domain classes:

[source,c++]
----
include::example$hello_world.cpp[tag=domain_classes]
----

Note that the Animal classes do not depend on iostreams anymore. This is a major
advantage of open-methods over virtual functions: they make it possible to
better organize dependencies.

Let's implement `poke`. First we need to include the library's main header. It
defines a few macros, and injects a name - `virtual_ptr` - in the global
namespace.

[source,c++]
----
include::example$hello_world.cpp[tag=method]
----

This defines a free function called `poke`, which takes two arguments. The first
is the `ostream`. The second argument corresponds to the implicit `this` pointer
in a virtual function. It is now an explicit argument. Just like with virtual
functions, the exact function to execute is selected on the basis of the
argument's _dynamic_ type.

Unlike virtual functions, there is no such thing as a pure open-method that
would make a class abstract. It is not possible to determine if an overrider is
available from looking at just the current translation unit.

Let's add overriders for `Cat` and `Dog`:

[source,c++]
----
include::example$hello_world.cpp[tag=overriders]
----

`Bulldog::poke` calls the `poke` it overrides in its `Dog` base. The equivalent
for open-methods is `next`, a function that is available only inside the body of
an overrider.  It calls the next most specific overrider, i.e. what would have
been called if the overrider did not exist.

[source,c++]
----
include::example$hello_world.cpp[tag=next]
----

All classes involved in open-method calls need to be registered using the
`BOOST_OPENMETHOD_CLASSES` macro:

[source,c++]
----
include::example$hello_world.cpp[tag=classes]
----

Classes can be registered incrementally, as long as all the direct bases of a
class are listed with it in some call(s) to `BOOST_OPENMETHOD_CLASSES`. For
example, `Bulldog` can be added in a second call, as long as `Dog` is listed as
well:

[source,c++]
----
// in animals.cpp
BOOST_OPENMETHOD_CLASSES(Animal, Cat, Dog);

// in bulldog.cpp
BOOST_OPENMETHOD_CLASSES(Dog, Bulldog);
----

`boost::openmethod::initialize();` must be called before any open-method call.
It builds the dispatch tables. Typically this is done in `main`:

[source,c++]
----
include::example$hello_world.cpp[tag=main,indent=0]
----

We call `poke` like any ordinary function. We can pass it the animals by
reference, because `virtual_ptr` has a conversion constructor for that:


[source,c++]
----
include::example$hello_world.cpp[tag=call]
----
