name: CI

env:
  BUILD_TYPE: Debug Release

permissions:
  contents: 'read'
  pages: 'write'
  id-token: 'write'

on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu:
    name: ubuntu-${{ matrix.compiler }}-${{ matrix.config }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
        compiler: [clang++, g++]
    steps:
      - uses: actions/checkout@v4
      - name: Install compiler
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh $1
        if: matrix.compiler == 'clang++'
      - name: Configure
        run: |
          pwd
          pwd
          cmake -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.config }}
      - name: Build
        run: |
          cmake --build build -j 16
      - name: Test
        run: |
          cd build
          ctest
  macos:
    name: macos-${{ matrix.config }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: |
          cmake -S . -B build  -DCMAKE_BUILD_TYPE=${{ matrix.config }}
      - name: Build
        run: |
          cmake --build build --target all -j 16
      - name: Test
        run: |
          cd build
          ctest
  windows:
    name: windows-${{ matrix.config }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1.4.1
        if: matrix.os == 'windows-latest'
      - name: Configure
        run: |
          cmake -B build
      - name: Build
        run: |
          cmake --config ${{ matrix.config }} --build build --target all -j 16
      - name: Test
        run: |
          cd build
          ctest
  artifacts:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Install asciidoctor
        run: |
          sudo apt-get install asciidoctor
          asciidoctor doc/openmethod.adoc -o build_outputs_folder/index.html
      - name: Generate documentation
        run: |
          sudo apt-get install asciidoctor
          asciidoctor doc/openmethod.adoc -o build_outputs_folder/index.html
      - name: Build flat headers
        run: |
          mkdir -p build_outputs_folder/boost/openmethod
          python3 dev/flatten.py \
            build_outputs_folder/boost/openmethod.hpp \
            include/boost/openmethod.hpp \
            include/boost/openmethod/unique_ptr.hpp \
            include/boost/openmethod/shared_ptr.hpp \
            include/boost/openmethod/compiler.hpp
          python3 dev/flatten.py \
            build_outputs_folder/boost/openmethod/policies.hpp \
            include/boost/openmethod/policies.hpp
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build_outputs_folder/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
